// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyeEGWogAT8RvND24Ax8aYbntDOGheROg',
    appId: '1:423610341670:web:9c244371c7b3eed9d609e7',
    messagingSenderId: '423610341670',
    projectId: 'healthy-d13bf',
    authDomain: 'healthy-d13bf.firebaseapp.com',
    storageBucket: 'healthy-d13bf.appspot.com',
    measurementId: 'G-26KPWEBWT1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKnG-LKkD8gjf5E-n0-DZhhyAR0H5FUrw',
    appId: '1:423610341670:android:7d6dc643fb670295d609e7',
    messagingSenderId: '423610341670',
    projectId: 'healthy-d13bf',
    storageBucket: 'healthy-d13bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbfLmLk-KBpaZkm9ikGMVjRY4yiysuTYM',
    appId: '1:423610341670:ios:43c2683c19ebb6f8d609e7',
    messagingSenderId: '423610341670',
    projectId: 'healthy-d13bf',
    storageBucket: 'healthy-d13bf.appspot.com',
    iosBundleId: 'com.example.buyerSellerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbfLmLk-KBpaZkm9ikGMVjRY4yiysuTYM',
    appId: '1:423610341670:ios:33db7378d1bb3712d609e7',
    messagingSenderId: '423610341670',
    projectId: 'healthy-d13bf',
    storageBucket: 'healthy-d13bf.appspot.com',
    iosBundleId: 'com.example.buyerSellerApp.RunnerTests',
  );
}
